version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tallyfix:latest
    container_name: tallyfix
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=mydatabase
      - DB_USER=root
      - DB_PASSWORD=password
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"
    volumes:
      - app-data:/app/data
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
  app-data:
